FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 10000
ENV ASPNETCORE_URLS=http://+:10000

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# COPIAR LOS ARCHIVOS .csproj DE TODOS LOS PROYECTOS
COPY ../Zoologico1_Modelos/Zoologico1_Modelos.csproj Zoologico1_Modelos/
COPY Zoologico1_API.csproj Zoologico1_API/

# RESTAURAR
RUN dotnet restore Zoologico1_API/Zoologico1_API.csproj

# COPIAR TODO EL REPO
COPY .. .

# CONSTRUIR
WORKDIR /src/Zoologico1_API
RUN dotnet build "Zoologico1_API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Zoologico1_API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Zoologico1_API.dll"]
