FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 10000
ENV ASPNETCORE_URLS=http://+:10000

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copiar solo el csproj primero
COPY Zoologico1_API.csproj ./

RUN dotnet restore "./Zoologico1_API.csproj"

# Copiar todo el proyecto
COPY . .

RUN dotnet build "Zoologico1_API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Zoologico1_API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Zoologico1_API.dll"]
